### ISSUE TITLE
Example queries?

### ISSUE THREAD

**Issue by Twipped** [guyb7/github-api-streamdeck-plugin#8]
It would be extremely helpful if the readme had the queries used to produce the example uses.

**Comment by guyb7** [comment]
Hey, all of the examples in the readme are presets. If you use the plugin, choose a preset from the dropdown and the query field will be filled in for you.

You can also view the presets here in case you just want to view the queries:
https://github.com/guyb7/github-api-streamdeck-plugin/blob/main/src/presets.js
